services:

  weather-service:
    image: acme/weather-mcp-server:latest
    ports:
      - "8090:8080"
      - "8091:8081"

  ai-service:
    image: acme/ai-server:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - weather-service

