
quarkus:
  application:
    name: ai-server

  otel:
    exporter:
      otlp:
        endpoint: http://localhost:4317
    metrics:
      enabled: true

  arc:
    dev-mode:
      monitoring-enabled:
  log:
    metrics:
      enabled: true

  langchain4j:
    openai:
      api-key: "sk_xxx"
